spring.application.name=EasyOrder

# ==========================================
# [1] 데이터베이스 접속 정보 (DataSource)
# ==========================================
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/easy_order
#spring.datasource.url=jdbc:mariadb://address=(host=::1)(port=3306)/easy_order

spring.datasource.username=order_user
spring.datasource.password=user123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


# ==========================================
# [2] JPA 및 하이버네이트(Hibernate) 설정
# ==========================================

# DB 테이블 자동 생성/변경 설정 (아주 중요한 옵션!)
# 'update': 스프링 부트가 실행될 때, 자바 Entity 클래스에 새로 추가/변경된 부분만 DB 테이블에 반영(업데이트).
# ※ 주의: 개발할 때는 편하지만, 실제 운영(Production) 서버에서는 테이블이 꼬일 수 있어 'validate'나 'none'로 옵션 변경
spring.jpa.hibernate.ddl-auto=update

# JPA가 데이터베이스로 날리는 실제 SQL 쿼리를 콘솔창(로그)에 보여줄지 여부
spring.jpa.show-sql=true

# 콘솔창에 출력되는 SQL 쿼리를 보기 좋게 정렬(들여쓰기 및 줄바꿈)해주는 설정
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# [3] 파일 업로드 설정
# ==========================================

# 파일 업로드 경로
file.upload.path=D:/upload/EasyOrder

# 파일 업로드 용량
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB